on: [push, pull_request]
jobs:
  unittest:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: |
        packages=`find . -type f -name "go.mod" -exec dirname {} \;`
        for dir in $packages; do
          cd $dir
          go test -race -convermode=atomic -v ./...
        done;
