on: [push, pull_request]
jobs:
  unittest:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Unittest
      run: make test
    - name: Benchmark
      run: make benchmark
    - name: Code Coverage Report
      uses: codecov/codecov-action@v2
      with:
        files: coverage.txt
        verbose: true
        flags: unittest
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
